apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: psicologia
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/psicologia"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"