apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: psicologia
type: Opaque
data:
  POSTGRES_DB: cHNpY29sb2dpYQ==  # psicologia
  POSTGRES_USER: YWRtaW4=  # admin
  POSTGRES_PASSWORD: YWRtaW4xMjM=  # admin123
  SPRING_DATASOURCE_USERNAME: YWRtaW4=  # admin
  SPRING_DATASOURCE_PASSWORD: YWRtaW4xMjM=  # admin123
  JWT_SECRET: bWluaGEtY2hhdmUtc2VjcmV0YS1zdXBlci1zZWd1cmEtcGFyYS1qd3QtdG9rZW5z  # minha-chave-secreta-super-segura-para-jwt-tokens